name: personal_portfolio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1

  web_pointer: ^1.1.4

  lava_lamp_effect: ^1.0.3
  timelines: ^0.1.0
  wave: ^0.2.2
  http: ^1.5.0
  url_launcher: ^6.3.2
  expandable: ^5.0.1
  # carousel_slider: ^5.1.1
  expansion_tile_card: ^3.0.0
  skeletonizer: ^2.1.0+1
  # visibility_detector: ^0.4.0+2
  animated_text_kit: ^4.3.0
 
  another_flutter_splash_screen: ^1.2.1
  # alp_animated_splashscreen: ^0.0.6
  lottie: ^3.3.2
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  flutter_swiper_view: ^1.1.8
  # web_smooth_scroll: ^2.0.0
  # flutter_staggered_animations: ^1.1.1
  # auto_animated: ^3.2.0 
  confirmation_success: ^0.0.2
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    # Images (use wildcard to include all files)
    - assets/images/
    - assets/images/MaskedSaleh.webp

    # Project images - each folder explicitly listed
    - assets/project_images/
    - assets/project_images/beauty/

    - assets/project_images/greenproject/
    - assets/project_images/playbaloot_images/
    - assets/project_images/viva/
    - assets/project_images/wavy/
    - assets/project_images/Ashwate/
    - assets/project_images/Plasticless/
    - assets/project_images/Jidni/

    # Main photos of each project (edited in canva by me :)
    - assets/project_images/mainImage/
    - assets/project_images/mainImage/ashwat.webp
    - assets/project_images/mainImage/beauty.webp
    - assets/project_images/mainImage/green.webp

    - assets/project_images/mainImage/playbaloot.webp
    - assets/project_images/mainImage/viva.webp
    - assets/project_images/mainImage/wavvy.webp

    # Splash screen 
    - web/splash.json
    - assets/splash_screen/cat.json
    #  splash screen images are in web folder bcuz i use them wtih index.html
    
    # Icons/SVGs
    - assets/icons/

